### ISSUE TITLE
Unable to install on bitnami redmine

### ISSUE THREAD

**Issue by duyluonglc** [ste26054/redmine_leaves_holidays#22]
I installed bitnami-redmine-3.1.1-0
an error when run migrate:
D:\Bitnami\redmine\apps\redmine\htdocs>bundle install
D:\Bitnami\redmine\apps\redmine\htdocs>rake redmine:plugins:migrate --trace
DL is deprecated, please use Fiddle
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
D:/Bitnami/redmine/apps/redmine/htdocs/plugins/redmine_leaves_holidays/lib/LeavesHolidaysExtensions.rb:2: warning: Refinements are experimental, and the behavior may change in future versions of Ruby!
rake aborted!
NoMethodError: undefined method `using' for LeavesHolidaysLogic:Module
D:/Bitnami/redmine/apps/redmine/htdocs/plugins/redmine_leaves_holidays/lib/LeavesHolidaysLogic.rb:2:in `<module:LeavesHolidaysLogic>'
D:/Bitnami/redmine/apps/redmine/htdocs/plugins/redmine_leaves_holidays/lib/LeavesHolidaysLogic.rb:1:in `<top (required)>'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
D:/Bitnami/redmine/apps/redmine/htdocs/plugins/redmine_leaves_holidays/init.rb:3:in `<top (required)>'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
D:/Bitnami/redmine/apps/redmine/htdocs/lib/redmine/plugin.rb:155:in `block in load'
D:/Bitnami/redmine/apps/redmine/htdocs/lib/redmine/plugin.rb:146:in `each'
D:/Bitnami/redmine/apps/redmine/htdocs/lib/redmine/plugin.rb:146:in `load'
D:/Bitnami/redmine/apps/redmine/htdocs/config/initializers/30-redmine.rb:21:in `<top (required)>'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/engine.rb:652:in `block in load_config_initializer'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/engine.rb:651:in `load_config_initializer'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/engine.rb:615:in `each'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/engine.rb:615:in `block in <class:Engine>'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
D:/Bitnami/redmine/ruby/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
D:/Bitnami/redmine/ruby/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
D:/Bitnami/redmine/ruby/lib/ruby/2.0.0/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
D:/Bitnami/redmine/ruby/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
D:/Bitnami/redmine/ruby/lib/ruby/2.0.0/tsort.rb:209:in `block in each_strongly_connected_component_from'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `each'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `tsort_each_child'
D:/Bitnami/redmine/ruby/lib/ruby/2.0.0/tsort.rb:203:in `each_strongly_connected_component_from'
D:/Bitnami/redmine/ruby/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
D:/Bitnami/redmine/ruby/lib/ruby/2.0.0/tsort.rb:180:in `each'
D:/Bitnami/redmine/ruby/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
D:/Bitnami/redmine/ruby/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
D:/Bitnami/redmine/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/application.rb:328:in `require_environment!'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/application.rb:457:in `block in run_tasks_blocks'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
D:/Bitnami/redmine/ruby/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
D:/Bitnami/redmine/ruby/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
D:/Bitnami/redmine/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
D:/Bitnami/redmine/ruby/bin/rake:23:in `load'
D:/Bitnami/redmine/ruby/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment

**Comment by ste26054** [comment]
The ruby version installed in Bitnami (2.0.0) is older than the one I am using for testing (2.2.1), and I did not encounter this bug due to refinements still being experimental (And ruby 2.2.1 seems more permissive about this than the version you have).

As a workaround, you can try to move, in LeavesHolidaysLogic.rb the statement "using LeavesHolidaysExtensions" to the top of the file.

**Comment by duyluonglc** [comment]
Thanks for your responded. 
I've try: move the statement "using LeavesHolidaysExtensions" to the top of the file" then migrate can work success. It may some incompatibles in ruby version so cannot access my redmine/home. I'll try to upgrade ruby on Bitnami Redmine Stack.
