### ISSUE TITLE
how to install/use this plugin?

### ISSUE THREAD

**Issue by triniteee** [ste26054/redmine_leaves_holidays#30]
Hi, I just installed it on redmine on ubuntu, and can only find the configuration in adminstration ->　plugins. Actually I'm not sure how to use/conf, or whether the install is successful. Is there any user guide for this plugin? Thanks a lot.

**Comment by ste26054** [comment]
Hi, sorry this plugin is still under heavy development and a major release should follow by the end of the month or so. As it will change the way the plugin works in terms of configuration needed / features, I do not plan to release a user guide beforehand.

I guess the install is successful if you can access the configuration page + new permissions have appeared.

**Comment by triniteee** [comment]
Looking forward to the new release, and thanks a lot!
