### ISSUE TITLE
configurable counting of multiple leave types

### ISSUE THREAD

**Issue by triniteee** [ste26054/redmine_leaves_holidays#51]
Hi,

First of all, thanks a lot for this plugin!

I'm playing this plugin and it provides most of features I want. It's already very good. For my purpose, I also want to count more than one leave type, such as annual leave, sick leave etc. In current configuration, it can support only one leave type, right? Please correct me if I'm wrong. The other question is whether you plan to support multi-level approval, or it is already supported but I miss the correct configuration.

**Comment by ste26054** [comment]
Hello,

Thanks for your feedback ! It does support several leave types: Just create issues with subject = 'The type of leave' in the project specified, with the tracker specified in the plugin administration page. Then, make it available to users in the same administration page. The new leave reason should be displayed.

The multi level approval is already supported. In a configuration such as:
- A is managed by B
- B is managed by C
- And so on...

C manages directly B, and indirectly A. C can still approve A's leave requests, though, but will not receive notifications unless B is on leave at the time A submits a leave request.

**Comment by triniteee** [comment]
Hi,

Thanks a lot for the feedback. For the first question, your description is correct and I didn't express it clearly. Does it support to configure settings like 15 days annual leave, and 10 days sick leave per year? Currently it has only one settings of "Default Number of Leave Days / Year". How to configure different leave days for different leave types?

For the multi level approval settings, I understood now. Thanks.

**Comment by ste26054** [comment]
Hi,

I understand now, we cannot do that for the moment, I cannot tell you when it will be implemented, but this is in the plans !

Thanks

**Comment by triniteee** [comment]
Hi,

Understood. Hope everything goes fine with you and thanks a lot.
