### ISSUE TITLE
Cannot upload or do git clone

### ISSUE THREAD

**Issue by logirard** [ste26054/redmine_leaves_holidays#52]
We cannot download or make a git clone of this plugin. Will we be able to use this plugin in the future ?

**Comment by ste26054** [comment]
There is nothing which should prevent you from cloning this repository. Perhaps are you behind a corporate proxy which is blocking https requests?

As a workaround, you can try to download the repo as zip on the main page.

**Comment by logirard** [comment]
It works fine today. Sorry for the disturbance.
